'use strict';

const { BrowserWindow } = require('electron');
const path = require('node:path');
const fs = require('node:fs');
const { paths } = require('./paths.cjs');

function formatNetscapeCookies(cookies) {
  let output = '# Netscape HTTP Cookie File\n# Generated by Multi-Platform Downloader\n\n';
  for (const c of cookies) {
    let domain = c.domain || '';
    if (domain && !domain.startsWith('.')) domain = '.' + domain;
    const flag = domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const cookiePath = c.path || '/';
    const secure = c.secure ? 'TRUE' : 'FALSE';
    const expiration = c.expirationDate ? Math.round(c.expirationDate) : 0;
    const name = c.name;
    const value = c.value;
    output += `${domain}\t${flag}\t${cookiePath}\t${secure}\t${expiration}\t${name}\t${value}\n`;
  }
  return output;
}

function mergeAndSaveCookies(newCookies, filePath) {
  const netscapeContent = formatNetscapeCookies(newCookies);
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, netscapeContent, 'utf8');
}

const PLATFORM_LOGIN_CONFIGS = {
  bilibili: {
    name: 'B站/Bilibili (解锁4K/1080P60高画质)',
    loginUrl: 'https://passport.bilibili.com/login',
    checkSuccess: (cookies) => cookies.some(c => c.name === 'SESSDATA' || c.name === 'bili_jct'),
  },
  instagram: {
    name: 'Instagram (解锁多图与私密内容)',
    loginUrl: 'https://www.instagram.com/accounts/login/',
    checkSuccess: (cookies) => cookies.some(c => c.name === 'sessionid' || c.name === 'ds_user_id'),
  },
  youtube: {
    name: 'YouTube / Google (解锁年龄限制与高清视频)',
    loginUrl: 'https://accounts.google.com/ServiceLogin?service=youtube',
    checkSuccess: (cookies) => cookies.some(c => c.name === 'SID' || c.name === 'SSID' || c.name === 'LOGIN_INFO'),
  },
  twitter: {
    name: 'Twitter / X',
    loginUrl: 'https://twitter.com/i/flow/login',
    checkSuccess: (cookies) => cookies.some(c => c.name === 'auth_token'),
  },
  douyin: {
    name: '抖音 (解锁无水印超清)',
    loginUrl: 'https://www.douyin.com/',
    checkSuccess: (cookies) => cookies.some(c => c.name === 'sessionid' || c.name === 'passport_csrf_token'),
  },
  xiaohongshu: {
    name: '小红书 (解锁原图与视频)',
    loginUrl: 'https://www.xiaohongshu.com/',
    checkSuccess: (cookies) => cookies.some(c => c.name === 'web_session' || c.name === 'a1'),
  },
};

function openLoginCaptureWindow(platformKey = 'bilibili', parentWindow = null) {
  const config = PLATFORM_LOGIN_CONFIGS[platformKey] || PLATFORM_LOGIN_CONFIGS.bilibili;

  return new Promise((resolve) => {
    let captured = false;
    let authWindow = new BrowserWindow({
      width: 540,
      height: 740,
      parent: parentWindow || undefined,
      modal: Boolean(parentWindow),
      title: `[登录获取凭证] 请登录 ${config.name}（登录成功将自动保存并关闭）`,
      backgroundColor: '#111820',
      autoHideMenuBar: true,
      webPreferences: {
        partition: 'persist:downloader_auth',
        contextIsolation: true,
        nodeIntegration: false,
        sandbox: true,
      },
    });

    const authSession = authWindow.webContents.session;

    const checkCookies = async () => {
      if (captured || authWindow.isDestroyed()) return;
      try {
        const cookies = await authSession.cookies.get({});
        if (config.checkSuccess(cookies)) {
          captured = true;
          mergeAndSaveCookies(cookies, paths.cookieFile);
          authWindow.setTitle(`✅ ${config.name} 登录成功！正在保存 Cookie...`);
          setTimeout(() => {
            if (!authWindow.isDestroyed()) authWindow.close();
            resolve({ ok: true, platform: platformKey, platformName: config.name, count: cookies.length });
          }, 800);
        }
      } catch (err) {
        console.error('Error checking cookies:', err);
      }
    };

    authWindow.webContents.on('did-navigate', checkCookies);
    authWindow.webContents.on('did-finish-load', checkCookies);

    const timer = setInterval(checkCookies, 1200);

    authWindow.on('closed', () => {
      clearInterval(timer);
      authWindow = null;
      if (!captured) {
        resolve({ ok: false, message: '用户取消了登录窗口' });
      }
    });

    authWindow.loadURL(config.loginUrl);
  });
}

module.exports = { openLoginCaptureWindow, PLATFORM_LOGIN_CONFIGS };
