# login_capture.py for platform-downloader
import sys
import os
import time
import threading

PLATFORMS = {
    'bilibili': {
        'name': 'B站/Bilibili (解锁4K/1080P60高画质与大会员)',
        'url': 'https://passport.bilibili.com/login',
        'check': lambda cookies: any(c.get('name') in ('SESSDATA', 'bili_jct') for c in cookies),
    },
    'instagram': {
        'name': 'Instagram (解锁纯多图帖与私密内容)',
        'url': 'https://www.instagram.com/accounts/login/',
        'check': lambda cookies: any(c.get('name') in ('sessionid', 'ds_user_id') for c in cookies),
    },
    'youtube': {
        'name': 'YouTube / Google (解锁年龄限制与高清视频)',
        'url': 'https://accounts.google.com/ServiceLogin?service=youtube',
        'check': lambda cookies: any(c.get('name') in ('SID', 'SSID', 'LOGIN_INFO') for c in cookies),
    },
    'twitter': {
        'name': 'Twitter / X',
        'url': 'https://twitter.com/i/flow/login',
        'check': lambda cookies: any(c.get('name') == 'auth_token' for c in cookies),
    },
    'douyin': {
        'name': '抖音 (解锁无水印超清)',
        'url': 'https://www.douyin.com/',
        'check': lambda cookies: any(c.get('name') in ('sessionid', 'passport_csrf_token') for c in cookies),
    },
    'xiaohongshu': {
        'name': '小红书 (解锁原图与视频)',
        'url': 'https://www.xiaohongshu.com/',
        'check': lambda cookies: any(c.get('name') in ('web_session', 'a1') for c in cookies),
    },
}

def format_netscape(cookies):
    lines = ["# Netscape HTTP Cookie File\n# Generated by Multi-Platform Downloader\n\n"]
    for c in cookies:
        domain = c.get('domain', '')
        if domain and not domain.startswith('.'):
            domain = '.' + domain
        flag = 'TRUE' if domain.startswith('.') else 'FALSE'
        path = c.get('path', '/')
        secure = 'TRUE' if c.get('secure') else 'FALSE'
        exp = int(c.get('expires') or 0)
        name = c.get('name', '')
        val = c.get('value', '')
        lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{exp}\t{name}\t{val}\n")
    return "".join(lines)

def run_login(platform_key='bilibili'):
    try:
        import webview
    except ImportError:
        print("ERROR_NO_WEBVIEW")
        return False

    cfg = PLATFORMS.get(platform_key, PLATFORMS['bilibili'])
    captured = False

    def monitor(window):
        nonlocal captured
        for _ in range(300):
            time.sleep(1.2)
            try:
                cookies = window.get_cookies()
                cookie_dicts = []
                for c in cookies:
                    if hasattr(c, 'items'):
                        cookie_dicts.append(dict(c))
                    elif hasattr(c, 'name'):
                        cookie_dicts.append({
                            'name': c.name, 'value': getattr(c, 'value', ''),
                            'domain': getattr(c, 'domain', ''), 'path': getattr(c, 'path', '/'),
                            'secure': getattr(c, 'secure', False), 'expires': getattr(c, 'expires', 0)
                        })
                if cfg['check'](cookie_dicts):
                    captured = True
                    text = format_netscape(cookie_dicts)
                    base_dir = os.path.dirname(os.path.abspath(__file__))
                    out_path = os.path.join(base_dir, 'cookies.txt')
                    with open(out_path, 'w', encoding='utf-8') as f:
                        f.write(text)
                    print("SUCCESS_CAPTURED")
                    time.sleep(0.8)
                    window.destroy()
                    break
            except Exception:
                pass

    window = webview.create_window(
        f"[登录获取凭证] 请在窗口中登录 {cfg['name']}（登录成功将自动保存并关闭）",
        cfg['url'],
        width=540, height=740
    )
    t = threading.Thread(target=monitor, args=(window,), daemon=True)
    t.start()
    webview.start()
    return captured

if __name__ == '__main__':
    plat = sys.argv[1] if len(sys.argv) > 1 else 'bilibili'
    run_login(plat)
